# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pandemic2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pandemic2020
pod 'Alamofire', '~> 4.5'
end
